name: bbs
version: 0.0.1
description: A library useful for applications or for sharing on pub.dartlang.org.
dependencies:
  bignum: ">=0.0.6 <0.1.0"
dev_dependencies:
  unittest: ">=0.11.5+4 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"