name: bbs
version: 0.0.1
author: Axel Christ <adracus@gmail.com>
description: Implementation of the BlumBlumShub CSPRNG (Cryptographically Secure Pseudo Random Number Generator)
homepage: https://github.com/Adracus/bbs
documentation: https://github.com/Adracus/bbs
dependencies:
  bignum: '>=0.0.6 <0.1.0'
dev_dependencies:
  mock: '>=0.11.0+2 <0.12.0'
  unittest: '>=0.11.5+4 <0.12.0'

